<?php

/**
 * This is the model base class for the table "folios".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Folios".
 *
 * Columns in table "folios" available as properties of the model,
 * followed by relations of table "folios" available as properties of the model.
 *
 * @property integer $id
 * @property string $lugar
 * @property integer $psicologica
 * @property integer $tecnica
 * @property integer $entrevista
 * @property integer $puntaje
 * @property integer $usuarios_id
 *
 * @property Usuarios $usuarios
 */
abstract class BaseFolios extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'folios';
    }

    public static function representingColumn() {
        return 'lugar';
    }

    public function rules() {
        return array(
            array('lugar, usuarios_id', 'required'),
            array('psicologica, tecnica, entrevista, puntaje, usuarios_id', 'numerical', 'integerOnly'=>true),
            array('lugar', 'length', 'max'=>255),
            array('psicologica, tecnica, entrevista, puntaje', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, lugar, psicologica, tecnica, entrevista, puntaje, usuarios_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'usuarios' => array(self::BELONGS_TO, 'Usuarios', 'usuarios_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'lugar' => Yii::t('app', 'Lugar'),
                'psicologica' => Yii::t('app', 'Psicologica'),
                'tecnica' => Yii::t('app', 'Tecnica'),
                'entrevista' => Yii::t('app', 'Entrevista'),
                'puntaje' => Yii::t('app', 'Puntaje'),
                'usuarios_id' => Yii::t('app', 'Usuarios'),
                'usuarios' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('lugar', $this->lugar, true);
        $criteria->compare('psicologica', $this->psicologica);
        $criteria->compare('tecnica', $this->tecnica);
        $criteria->compare('entrevista', $this->entrevista);
        $criteria->compare('puntaje', $this->puntaje);
        $criteria->compare('usuarios_id', $this->usuarios_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}