<?php

/**
 * This is the model base class for the table "estudios".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Estudios".
 *
 * Columns in table "estudios" available as properties of the model,
 * followed by relations of table "estudios" available as properties of the model.
 *
 * @property integer $id
 * @property string $Institucion
 * @property integer $anoGrado
 * @property string $Titulo
 * @property integer $usuarios_id
 *
 * @property Usuarios $usuarios
 */
abstract class BaseEstudios extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'estudios';
    }

    public static function representingColumn() {
        return 'Institucion';
    }

    public function rules() {
        return array(
            array('Institucion, anoGrado, Titulo, usuarios_id', 'required'),
            array('anoGrado, usuarios_id', 'numerical', 'integerOnly'=>true),
            array('Institucion, Titulo', 'length', 'max'=>255),
            array('id, Institucion, anoGrado, Titulo, usuarios_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'usuarios' => array(self::BELONGS_TO, 'Usuarios', 'usuarios_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'Institucion' => Yii::t('app', 'Institucion'),
                'anoGrado' => Yii::t('app', 'Ano Grado'),
                'Titulo' => Yii::t('app', 'Titulo'),
                'usuarios_id' => Yii::t('app', 'Usuarios'),
                'usuarios' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('Institucion', $this->Institucion, true);
        $criteria->compare('anoGrado', $this->anoGrado);
        $criteria->compare('Titulo', $this->Titulo, true);
        $criteria->compare('usuarios_id', $this->usuarios_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}